# 参考
# Build and push Docker images
# https://github.com/marketplace/actions/build-and-push-docker-images
# Docker Metadata action
# https://github.com/marketplace/actions/docker-metadata-action

name: Docker Publish

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          repository: 'mouday/spider-admin-pro'
          ref: 'v3.0'
          path: 'spider_admin_pro'

      # 拉取web前端dist的代码
      - name: Checkout Web Dist
        uses: actions/checkout@v4
        with:
          repository: 'mouday/spider-admin-pro-web'
          ref: 'v3.0'
          token: ${{ secrets.GH_PAT }}
          path: 'spider_admin_pro_web'

      - name: Build Web
        run: |
          cd spider_admin_pro_web
          pnpm install --no-frozen-lockfile
          pnpm run build:prod
          mkdir -p ../spider_admin_pro/spider_admin_pro/public
          cp -r ./dist/* ../spider_admin_pro/spider_admin_pro/public/

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
            images: mouday/spider-admin-pro

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:spider-admin-pro"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
